export const SET_UPLOADING = 'SET_UPLOADING'
export const SET_UPLOAD_IMAGES = 'SET_UPLOAD_IMAGES'
export const SET_DISPLAY_IMAGES = 'SET_DISPLAY_IMAGES'
export const SET_DISPLAY_IMAGES_ERROR = 'SET_DISPLAY_IMAGES_ERROR'

export const GET_FAVORITES = 'GET_FAVORITES'
export const SET_FAVORITES = 'SET_FAVORITES'

export const GET_VOTES = 'GET_VOTES'
export const SET_VOTES = 'SET_VOTES'
